# 3. Polynomial Regression

### How about data you have has  more complex form. 

### e.g.,

# Quadratic Equation

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression


m = 100
X = 6 * np.random.rand(m,1) - 3
y = 0.5 * X**2 + X +2 + np.random.randn(m,1)

This dataset wouldn't work well for linear line

#### So we are going to tranform dataset with PolynomialFeature adding new features.

#### This features are obtained with squared each features

If we use PolynomialFeatures with degree 3, then it add multiplied each feature

In [19]:
from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree = 2, include_bias=False)
X_poly = poly_features.fit_transform(X)
X[0]

array([2.28589862])

In [20]:
X_poly[0]

array([2.28589862, 5.22533251])

In [21]:
lin_reg =  LinearRegression()
lin_reg.fit(X_poly, y)
lin_reg.intercept_, lin_reg.coef_

(array([2.12303287]), array([[0.95092469, 0.5053484 ]]))